project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true

website:
  title: "PIP-Bloggers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
